### ISSUE TITLE
你好，请教一下关于android ffmpeg

### ISSUE THREAD

**Issue by ghost** [WaterPeak/Sorry-Android#1]
https://github.com/hl4a/sorry
我是(直接用ffmpeg加字幕)
但是每次都要卡大概30秒
(服务器上生成没有这个阶段)
请问如何避免呢？

**Comment by Ferrum5** [comment]
> https://github.com/hl4a/sorry
> 我是(直接用ffmpeg加字幕)
> 但是每次都要卡大概30秒
> (服务器上生成没有这个阶段)
> 请问如何避免呢？

WritingMinds那个从包里复制一个可执行程序到手机里，用ShellCommand执行，跟我用这个不太一样。
我用WritingMinds那个mp4转gif就挂了，报SoundHandler错误。
